services:
    rainlike.breadcrumbs:
        class: Rainlike\BreadcrumbsBundle\Service\BreadcrumbsBuilder

    rainlike.breadcrumbs.processor:
        class: Rainlike\BreadcrumbsBundle\Service\BreadcrumbsProcessor
        autowire: true
        autoconfigure: true
        public: true

    rainlike.breadcrumbs.helper:
        class: Rainlike\BreadcrumbsBundle\Helper\BreadcrumbsHelper
        autowire: true
        autoconfigure: true
        public: true

    rainlike.breadcrumbs.extension:
        class: Rainlike\BreadcrumbsBundle\Twig\BreadcrumbsExtension
        autowire: true
        autoconfigure: true
        public: true
        tags:
            - { name: twig.extension }
